name: SonarCloud Analysis

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: # Permet le déclenchement manuel depuis l'interface GitHub

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    if: false #  ⬅️⬅️⬅️⬅️ Disabled for now
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better analysis

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=argenteuil-basketball
            -Dsonar.organization=YOUR_ORG_KEY
            -Dsonar.sources=src,core
            -Dsonar.tests=tests,core
            -Dsonar.test.inclusions=**/__tests__/**,**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx,tests/**
            -Dsonar.cpd.exclusions=**/__tests__/**,**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx,tests/**
            -Dsonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/*.config.ts,**/*.config.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
